### ISSUE TITLE
Building instructions appreciated

### ISSUE THREAD

**Issue by baltbreeze** [huntj88/DhiffieChat#5]
Your project is very interesting, however instructions to build it and setup testing environment is needed.
I've started by building the Android part by Android Studio and by gradle separately. The numerous errors stopped project from building. Instead of posting errors here I think it would be great to have some build setup scenario (dependencies?) from the developer.
Kind Regards,

**Comment by huntj88** [comment]
@baltbreeze Thanks for the interest!

Sorry about that, I originally developed this app using the Canary version of Android Studio to enable Jetpack Compose. It looks like the tooling has caught up and I was able to get it compiling for 2020.3.1 patch 1 (current latest stable release). 

Just pushed my changes so it should work out of the box now.

Adding new environments does need to be documented still, and I can see about doing that a bit later.

Both my Staging and Prod environments are still running if you want to play with the existing environments

**Comment by baltbreeze** [comment]
Got it working (build successful). Can I donate the development?

**Comment by huntj88** [comment]
Sure! Its nice knowing someone is getting some value out of my work! I don't have any sort of donation method right now, although I could setup GitHub Sponsors or something

**Comment by huntj88** [comment]
Updated the README to include deployment instructions here https://github.com/huntj88/DhiffieChat/pull/10
